bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/RefreshFileJob.java
Improves performance when importing a lot of projects
and when refreshing a lot of projects.
=> Reducing number of RefreshFileJob threads

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
This reverts commit dfa63eb06defb1a131c9efd35c49efc266f21aca.
Otherwise known as #999 
Turns out I didn't test enough until AFTER I pushed it.
I need to think about how to solve eclipse's squirreliness.
Issue to solve:
- bnd has projects that pulls packages from other projects and exports them. And there are other projects that have references to the project that did the pulling. My approach didn't address this. (but solved other issues!) <grumble, grumble>
=> Revert "Fix transitive jar file references issues"

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, cnf/build.bnd
These are not turned on by default, since I wanted to slow roll the incorporation
of something so fundamental to bndtools.
To enable, add a project or global variable:
eclipse.newaccessrules: true
You can also debug access rules with
eclipse.debug: true
The new rules add library classpath entries instead of project classpath entries
except for version=project references, which still add project references. All
transitive dependencies are turned off with the new rules too. This should be
closer to the bnd command line build handling of jars on the classpath during
a build.
These new access rules should address several transitive dependency issues that
I've encountered and I've seen written up as issues.
Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>
=> Created a set of new access rules for eclipse

bndtools.core/src/bndtools/editor/BndEditor.java, bndtools.core/src/bndtools/wizards/bndfile/EnableSubBundlesOperation.java, bndtools.core/src/bndtools/wizards/project/AbstractNewBndProjectWizard.java, bndtools.core/src/org/bndtools/core/ui/resource/R5LabelFormatter.java, bndtools.core/src/org/bndtools/core/ui/wizards/blueprint/BlueprintXmlFileWizard.java, bndtools.release/src/bndtools/release/ReleaseHelper.java
This change goes along with the companion bnd change. It enables
Workspace properties to be used in BndEditModel.
It also includes a R5LabelFormatter to show the variable on a runbnd
editor.
Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>
=> Enable workspace cnf variables in project .bnd and .bndrun -runrequires (and others)

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
Make a library and a project entry for each buildpath entry that resolves
to an eclipse project.
This seems to address the source lookup and source refactoring
problems discussed in #1005. And it seems to have all of the benefits
of what the new access rules are bringing.
More bake time now...
Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>
=> Adjust newaccessrules classpath entries for Container.TYPE.PROJECT

bndtools.builder/src/org/bndtools/builder/NewBuilder.java
Temp fix for the old NewBuilder to never generate NPEs and catch any exceptions.
=> [builder] get rid of potential NPE

bndtools.bndplugins/bnd.bnd, bndtools.builder/bnd.bnd, bndtools.core/bnd.bnd, bndtools.jareditor/bnd.bnd, bndtools.release/bnd.bnd, bndtools.utils/bnd.bnd, cnf/build.bnd, org.bndtools.headless.build.manager/bnd.bnd, org.bndtools.headless.build.plugin.ant/bnd.bnd, org.bndtools.headless.build.plugin.gradle/bnd.bnd, org.bndtools.versioncontrol.ignores.manager/bnd.bnd, org.bndtools.versioncontrol.ignores.plugin.git/bnd.bnd
The new classpath container identified a number of issues on the bnd
files for a number of projects.
- Use aQute.libg directly instead of relying on it being in bndlib
- Move junit to -testpath
- Add "packages=**" to swt fragment and bndtools.utils entries
=> build: Clean up bnd files

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BuildLogger.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
A project might have a bnd builder but not use the bnd classpath
container. When checking if the classpath has changed during incremental
build, we don't want to force the creation of a bnd classpath
container if the project does not already have one.
=> Dont force classpath container creation

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
A project in the bnd workspace may not be in the eclipse workspace.
Sometimes a project (which is not use by projects loaded in the eclipse
workspace) may not be loaded into the eclipse workspace.
=> classpath: bnd project may not be in eclipse workspace

org.bndtools.headless.build.plugin.ant/bnd.bnd, org.bndtools.headless.build.plugin.gradle/bnd.bnd
Projects imported an aQute.lib* package that should have been included.
=> install: Fix p2 install failure

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/jobs/newproject/AdjustClasspathsForNewProjectJob.java
#944 shows a deadlock where two threads (incremental builder and AdjustClasspathsForNewProjectJob) call the classpath container to update classpaths for projects. We need to protect against multiple threads from calling into the non-thread-safe bnd code.
=> Reorganize classpath container implementation to avoid deadlocks in calling bnd code

bndtools.api/src/org/bndtools/api/BndtoolsConstants.java, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core/src/bndtools/editor/pages/ProjectBuildPage.java
The container initializer will now put all errors in the model and the
incremental builder will be responsible for setting the error markers.
Currently the incremental builder loses the errors, so it needs to be
changed. @pkriens is working on this change. The incremental builder
also needs to make sure Project.prepare() is run each incremental build
to generate any classpath errors that exist into the model. Otherwise
the classpath errors will be lost if the model is cleared each build.
Since the incremental builder is now responsible for all error markers,
the bnd classpath problem marker type is also deleted.
Fixes https://github.com/bndtools/bndtools/issues/1037
=> classpath: Remove setting of classpath error markers

bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java, bndtools.utils/src/org/bndtools/utils/javaproject/JavaProjectUtils.java, org.bndtools.versioncontrol.ignores.manager/src/org/bndtools/versioncontrol/ignores/manager/VersionControlIgnoresManagerImpl.java
JavaProjectUtils.getSourceOutputLocations returned null in certain
circumstances. It now returns an empty map.
Fixes https://github.com/bndtools/bndtools/issues/455
=> Fix NPE: Return an empty map instead of null

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
With sub bundles, one could have multiple version=latest entries on the
-buildpath which reference the same project. This fix combines the
access rules for the different -buildpath entries so there is a single
project entry with the combined access rules.
Also include a fix for NPE on new project creation.
=> classpath: Combine access rules to have a single project entry

bndtools.api/src/org/bndtools/api/BndtoolsConstants.java, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BuildLogger.java, bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
– If a postponed build returned, the log said that nothing was build
– Markers now contain more Location info from bnd so we can pick it up in lists
=> Fixed logging when postponed returned & markers

build/build.gradle, org.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/root/settings.gradle, settings.gradle
Some bnd types have non-private fields with the "same" name as the
getter method. For example: sourcepath and getSourcepath. Groovy
was picking the field instead of the getter. This caused an error
when the impl details of the field changed while the method did not.
So we now always use method calls in the Groovy code to make sure we
always call the getter and not access the field.
=> gradle: Use method names for bnd types

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core/src/bndtools/central/Central.java
A can depend upon B. B can changes its exports. A's classpath needs to
be updated to reflects the new access rules. This fix will check if A's
dependencies have been updated and if so, suggest a classpath update
for A.
=> Classpath check for upstream changes

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/DeltaWrapper.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
The old impl uses the JarInfo cache, but updating one container will
update the cache so that a later container would not see that it needed
to be updated. So now we hold a lastModified timestamp in the container
that holds the timestamp of the newest item in the container. The
suggest change method will compare the timestamp of the container to the
timestamps of the container items and suggest an update if any item is
newer than the container timestamp.
=> classpath container: suggest container update needs to use a timestamp

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionWizard.java
This special handling of workspace bundles is
no longer required, because bnd will now resolve
an ordinary version range against the workspace
if it has a version that fits within the range.
=> Resolver: don't use version=latest in runbundles output

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
If an empty string was persisted as the access patterns for a project,
an access rule with the path of the empty string was mistakenly created.
This causes eclipse to throw an exception:
https://bugs.eclipse.org/465640
Fixes https://github.com/bndtools/bndtools/issues/1108
=> classpath: No access rules for empty persisted access patterns

build.gradle, settings.gradle
The gradle plugin runs too late to alter the gestalt of the workspace.
So we remove that from the plugin and change the settings.gradle and
build.gradle files to set the gestalt.
=> gradle: bnd plugin cannot set gestalt

build.gradle, settings.gradle
The static getWorkspace method caches the Workspace. When using the
gradle daemon, the daemon process never notices updates to bnd files
since the Workspace and thus all Projects are cached.
=> gradle: Create a new Workspace object each build

bndtools.core/_plugin.xml
This resolves a "The proxied handler for
'bndtools.views.RemoveRepoResourceHandler' could not be loaded" error
when right-clicking on JPM resources in the Repositories view.
Signed-off-by: Sean Bright <sean@malleable.com>
=> Correct FQCN for RemoveRepoResourceHandler

bndtools.core/src/bndtools/launch/util/LaunchUtils.java
bndrun files must not depend upon the project (bnd.bnd). They only
inherit from the workspace.
Fixes https://github.com/bndtools/bnd/issues/980
=> bndrun: export must not reference project properties

bndtools.core/src/bndtools/editor/contents/GeneralInfoPart.java
Not in love with this, but with 1.3 generally available it is a bit more
clear about capabilities.
Signed-off-by: Sean Bright <sean@malleable.com>
=> Update DS annotation option text to reflect 1.3

bndtools.core/src/org/bndtools/build/api/AbstractBuildErrorDetailsHandler.java
The error marker search code didn't handle Parameterized types as method parameters, and threw an IllegalStateException. As the paramterization is erased from the signature we should just use the SimpleType without the paramaters. Fixes #1215
=> Avoid tripping up when creating error markers

build.gradle, settings.gradle
We use the gradle uri method.
However, you still need to use absolute urls in the gradle.properties
file since that file is included in bndtools(Eclipse) and bnd has no
provision to resolve the relative uri.
=> build: Add support for relative file urls to the bnd gradle plugin

cnf/ext/repositories.bnd, gradle.properties, rebuild-with-local-plugin
You can now set bnd_repourl=../bnd/dist/bundles in gradle.properties to
build against your local bnd build.
Add rebuild script to test build with local build of bnd gradle plugin.
=> uri: Use new uri macro to allow relative path to local bnd build

bndtools.manual/developer/RELEASE_CHECKLIST.md, build/bnd.bnd, build/feature/bndtools/feature.xml
Bndtools references the templates from a repo rather than installed
plugins. So the template bundles are not part of the p2 feature for
Bndtools.
=> templates: The template projects are not part of the bndtools feature

org.bndtools.templates.osgi/resources/templates/ds/bnd.bnd
This fixes a testpath error when creating a project from the Component
Development template when your cnf project is created using the JPM4J
Configuration.
=> Use ${junit} in -testpath of DS template

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BuildLogger.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java, bndtools.core/src/bndtools/central/RepositoryUtils.java
Defines a bndCall method which takes a Callable and serializes access
for calls to bnd code which is not thread safe.
=> bnd: Centralize logic for serializing calls to non-thread safe bnd code

bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java
- make it clear that the validation message comes from Bndtools and not
from Eclipse;
- make it clear that an unknown container might impact your build's
portability;
- small typo fixed.
Signed-off-by: Jan Willem Janssen <janwillem.janssen@luminis.eu>
=> Issue #1274 - less ambiguous validation messages:

bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java
- make it clear that the validation message comes from Bndtools and not
from Eclipse;
- make it clear that an unknown container might impact your build's
portability;
- small typo fixed.
Signed-off-by: Jan Willem Janssen <janwillem.janssen@luminis.eu>
=> Fixes #1274 - less ambiguous validation messages:

cnf/build.bnd
=> build: Use SPDX license identifier for Bundle-License header

bndtools.api/bnd.bnd, bndtools.builder/bnd.bnd, bndtools.core/bnd.bnd, bndtools.jareditor/bnd.bnd, bndtools.release/bnd.bnd, bndtools.utils/bnd.bnd, org.bndtools.headless.build.plugin.ant/bnd.bnd, org.bndtools.headless.build.plugin.gradle/bnd.bnd, org.bndtools.templating/bnd.bnd
bndlib includes the latest DS annotations and the -buildpaths of
projects has osgi.cmpn;5 before bndlib which caused a failure in
DS annotation processing during a test. We now always put bndlib before
osgi jars in the -buildpath.
=> build: A fix to bnd seems to have surfaced a bug in the build

bndtools.core/src/bndtools/wizards/workspace/WorkspaceLocationPart.java, bndtools.core/src/bndtools/wizards/workspace/WorkspacePreviewPage.java, bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizard.java, bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizardPage.java, bndtools.test/bndws/test.baseline/bnd.bnd, bndtools.test/bndws/test.baseline/src/test/baseline/package-info.java
The current code seemed quite confused about another directory for the 
bnd workspace from the Eclipse workspace. It gave a warning if the cnf
already existed but created a mess if this warning was ignored.
The changes are:
- Different UI for an update and create. For an update, you 
cannot change the location of the cnf project anymore.
- Attempt to properly handle the bnd workspace when it is 
in a different location. The cnf project will now get the 
proper location
- If it is an update, files that are actually identical are not
marked red. This is a binary compare. (It would be nice if
we actually could use the Eclipse diff if there is a difference.)
=> #1332 OSGi enRoute workspace: cnf ends up in the Eclipse workspace

build/feature/bndtools/feature.xml, build/main.bnd, cnf/ext/repositories.bnd
Eclipse Orbit, in its infinite wisdom, chose a different BSN for the
slf4j.api bundle than SLF4J did in the jar in Maven Central. So other
Eclipse features use the bundle from Orbit which seems to conflict with
the one from maven. So we change to package the bundle from Orbit.
Fixes https://github.com/bndtools/bndtools/issues/1371
=> build: Use Eclipse Orbit slf4j api bundle to avoid conflict

build.gradle, settings.gradle
Reverts bndtools/bndtools#1414
BndProgess uses Gradle internal API. We must not do this in the official Gradle plugin. We risk breaking badly when people upgrade Gradle.
=> Revert "[progress] Add BndProgress to build"

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionWizard.java
Fixes: [#1367](https://github.com/bndtools/bndtools/issues/1367)
Some OSGi-modules require a dedicated start-order. With this fix, a
manually changed -runbundles section is not overriden. The diff is added
to the end of the list. Removed bundles are also considered.
Signed-off-by: Marc Schlegel maschlegel@gmail.com
=> 1367: do not reorder -runbundles on resolve

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
The change to defer the initialization of the bnd class path container
to after the bnd workspace is initialized can result in the failure to
establish the bnd class path container for a java project. When
initialize is called by Eclipse, the code must call setClasspathContainer
otherwise Eclipse will decide the java project does not have a bnd
class path container. So we always start by calling setClasspathContainer
to set an empty class path and establish the bnd class path container.
Then, after the bnd workspace is initialized, we are called again and
will set the actual class path for the container.
=> container: Cannot defer initialization of bnd classpath container

bndtools.core/src/bndtools/launch/BndDependencySourceContainer.java
Previously the code appeared to try and convert the external file path into a workspace path
before creating an AcrhiveSourceContainer object.
This just, rather naively, directly constructs an ExternalArchiveSourceContainer pointing at the
bundle jar.
It appears to fix the issue of finding source for external libraries. If you have, say, downloaded
a bundle from Central, and added source, then source will now be found. Previously it appeared
that source was only found for bundles in Local, as only then was the jar file actually in the workspace.
Signed-off-by: Tom Quarendon <tom@quarendon.net>
=> Attempt to get eclipse to find sources of jars in external repositories

bndtools.core/src/bndtools/launch/BndDependencySourceContainer.java
If there are multiple bundles in a bndrun configuration, and multiple of them
originate from the same project, that project is added to the debug source
search path multiple times. This commit just simply detects the duplication.
Signed-off-by: Tom Quarendon <tom.quarendon@teamwpc.co.uk>
=> Same project put in debug source path multiple times

bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/classpath/ClasspathContainerSerializationHelper.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java, bndtools.core/src/bndtools/central/WorkspaceListener.java, bndtools.core/src/bndtools/central/WorkspaceR5Repository.java, bndtools.core/src/bndtools/editor/BndEditor.java, bndtools.core/src/bndtools/editor/pages/ProjectRunPage.java, bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java, bndtools.core/src/bndtools/editor/workspace/WorkspaceMainPart.java, bndtools.core/src/bndtools/views/repository/RepositoriesView.java
We use a classpath container serializer/deserializer helper from M2E to
serialize the BndContainer when it is set. During initialization of the
classpath container, if the workspace is initialized, we do the normal
container initialization. If the workspace is not initialized, we
deserialize the serialized BndContainer and use that. We also add a
callback to request an update once the workspace is initialized. If the
serialized container has the proper classpath, then no update is made.
Fixes #1449
=> classpath container: Serialize to allow restore before workspace init

bndtools.core/src/bndtools/editor/contents/GeneralInfoPart.java
Because DS annotations are now the default, the drop down in the Bnd
editor is confusing. This fixes that and also changes the meaning of
"None" to mean disabled and update the model accordingly.
=> Bnd Editor: Show correct DS selection in drop down

bndtools.core/src/bndtools/views/repository/RepositoriesView.java
Java's built-in HttpUrlConnection will not follow redirects across
protocols (http -> https). bnd's HttpClient will, so use that instead
when dropping URLs on a repository.
=> Use HttpClient during repository DnD

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitHubWorkspaceTemplateLoader.java, org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitRepoPreferences.java, org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/PlainGitWorkspaceTemplateLoader.java, org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/ui/EditableParametersPart.java
`aQute.bnd.header.Parameters` adds trailing tildes to disambiguate duplicated
keys, so we need to remove them when displaying them or attempting to access
them.
I'm not in love with this, and it prevents Git clone URIs from ending with
tildes (I'm not sure how much of a problem that is in practice).
Fixes #1471
=> Remove trailing tildes from repository paths

bndtools.core/src/bndtools/central/RepositoryUtils.java, bndtools.core/src/bndtools/editor/project/RepositoryBundleSelectionPart.java, bndtools.core/src/bndtools/model/repo/RepositoryBundleUtils.java, bndtools.core/src/bndtools/wizards/repo/RepoBundleSelectionWizardPage.java
There is a lone problem marker in the Bndtools Eclipse workspace that reads:
`Export bndtools.central,  has 1,  private references [bndtools.model.repo]`
This is because RepositoryUtils exposed RepositoryBundle and
RepositoryBundleVersion as arguments to a couple static methods. This patch
moves those static methods to a new class in a non-exported package to
squelch the warning.
Signed-of-by: Sean Bright <sean.bright@gmail.com>
=> Move static methods to silence private reference warning

bndtools.core/src/bndtools/central/Central.java
getWorkspace will handle the necessary synchronization.
=> deadlock fix: Remove unneeded synchronization

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/indexer/BuiltBundleIndexer.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/WorkspaceR5Repository.java, bndtools.core/src/bndtools/editor/exports/ExportPatternsListPart.java, bndtools.core/src/bndtools/editor/project/RunBundlesPart.java
Use the proper overload and change implementation to use new
Workspace.getProjectFromFile method.
=> Clean up use of Central.getProject

bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java
The problem here is that the `RepoTemplateContentProvider.getFirstTemplate`
method returns (aptly) the first template, but that template might be
filtered out by the `ViewerFilter` associated with the `TreeViewer`.
So we jump through a few hoops to filter the `ContentProvider` contents so
that we select the first _visible_ template in the `TreeViewer`.
=> Change how we select the first element in template wizards

bndtools.repository.base/bnd.bnd, build/main.bnd, org.bndtools.headless.build.plugin.ant/bnd.bnd
Use version range for packaging so that when building against a local
bnd build, you use the latest snapshot.
=> build: Package latest bnd jars

bndtools.release/bnd.bnd
They are not runtime annotations and there does not appear to be any code
in the bundle which even uses them.
=> Remove import of component.annotations

bndtools.core/src/bndtools/central/WorkspaceRepositoryChangeDetector.java
This is to try and avoid a race condition with bnd refreshing projects.
=> Add delay to refreshing workspace repositories

cnf/build.bnd
Bnd 3.4 defaults to 1.3 as the base DS version. We want to work with
older DS versions since Eclipse Equinox DS currently does not support
DS 1.3.
=> build: Set DS default version to 1.0

CONTRIBUTING.md
The Development Environment section describes the necessary steps to set up a Bndtools development environment in Eclipse.
=> Add Development Environment section to contributing guide

bndtools.core/src/bndtools/launch/util/LaunchUtils.java
Closes #1600 Unnecessary null check in LaunchUtils::getTargetResource()
=> Remove unnecessary null check in LaunchUtils

bndtools.core/src/bndtools/launch/JUnitShortcut.java, bndtools.core/src/bndtools/launch/api/AbstractLaunchShortcut.java
Newly created launch configurations do not include a project
name via an expected attribute, which can cause and endless
loop on launching under certain circumstances.
Fixes: 1639
Signed-off-by: Jon Passki <jon@passki.us>
=> launch: Add project name to launch configuration

bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
This fixes a potential issue with MarkerSupport in which a ConcurrentModificationException may occur, as per issue #1632. 
This fix affects MarkerSupport.createMarkers, creates a copy of the input parameter Collection<String> msgs, and iterates on the copy rather than the original to avoid the possibility of a ConcurrentModificationException.
=> ConcurrentModificationException during build #1632

bndtools.core/_plugin.xml, org.bndtools.templating.gitrepo/resources/plugin.xml
1598: Preference pages under Bndtools don't show when filtering for 'bnd'
fixes bndtools/bndtools#1598
Extensions-Points enhanced with keywords to include subpages in filter. Though Bndtools preferences are already at the root, showing subpages on filter is a expected behaviour in Eclipse.
Signed-off-by: Marc Schlegel maschlegel@gmail.com
=> Preference pages under Bndtools don't show when filtering for 'bnd'

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, org.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/root/build.gradle, org.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/root/settings.gradle
The project builder may not need to update the files if there is no change detected.
Also, update gradle build template for new biz.aQute.bnd.workspace gradle plugin.
=> builder: Don’t delete build files before building project

bndtools.core/_plugin.xml, bndtools.core/src/bndtools/wizards/project/ImportBndWorkspaceWizard.java, bndtools.core/src/bndtools/wizards/project/ImportBndWorkspaceWizardPageOne.java
fixes bndtools/bndtools#916
Imports a bnd-workspace to Eclipse
Usage:
1. File -> Import...
1. BndTools -> Existing Bnd-Workspace
1. Choose a valid Bnd-Workspace root-folder
This importer will map informations from Bnd to Eclipse. To do so, **it will wipe all existing Eclipse project-specific settings in this workspace an recreate them**.
For each Bnd-project the import will make sure to set the correct source-, test-, and output-folders, where project level takes precedence over workspace-level settings.
Open
- Eclipse smart import (not sure if this is available in the current Eclipse 4.4.2 base)
This work is stalled since quite some time because I tried to display some more information in a read-only-panel (like mapped folders) but I wasnt very happy with this and couldnt find any …
=> 916: seamless project import into eclipse

bndtools.core/_plugin.xml
Change bindings extension to consistently use Alt+Shift+X/D K to run/debug tests.
See #1674: Different key bindings to run/debug Bnd OSGi Tests
=> Align key bindings to run/debug Bnd OSGi Tests

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/WorkingSetTracker.java
You can now define working sets in the bnd.bnd file (or in build.bnd). There are 2 modes:
-workingset: bar, foo, baz
This will add the project to the given working sets as one can expect.
The other mode is intended to be used in bnd (but not limited to)
-workingset: Implementations; member=${filter;${p};.*\.impl\..*}
The member attribute is evaluated to a boolean with Processor.isTrue. If true, the project is a member of the corresponding working set. 
The code will create working sets as demanded but will reuse existing working set with the matching name. If no -workingset property is given, the working sets are not touched in any way for that project.
=> [workingset] Adds working sets to the bnd file.

bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java, bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageTwo.java
This was caused by an NPE when no provisional project was created. So
instead we just let the JDT project wizard take care of creating and
deleting the provisional project as necessary.
Fixes #1648
=> Fix clicking "< Back" in New Bnd OSGi Project

bndtools.core/src/bndtools/editor/project/RepositoriesEditModel.java, bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java
Some RepositoryPlugin::toString returns stateful information of the repository so they won't
be picked up if you have ordered/selected repositories in .bnd(run) files
Signed-off-by: PK Søreide <per.kristian.soreide@gmail.com>
This PR requires https://github.com/bndtools/bnd/pull/2051 to be merged first
=> Use RepositoryPlugin::getName to get repository names where applicable

bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/editor/project/RunFrameworkPart.java, bndtools.core/src/bndtools/model/repo/RepositoryTreeContentProvider.java
The repoView has a cache of results now due to recent async work in
this commit ac4a86c5d9436ea6653cb15c44cde484d0308e1b
However this cache was not being cleared when user 'refreshes' repos
in either RepoView or main toolbar menu, this change addresses that
Closes https://github.com/bndtools/bndtools/pull/1719
=> repoview: Clear cache when user refreshes repo

bndtools.builder/src/org/bndtools/builder/handlers/baseline/BundleVersionErrorHandler.java
If Bundle-Version is defined in build.bnd or ext, no markers are created and the project will not build
The marker will be set on the Projects bnd.bnd file
Signed-off-by: PK Søreide <per.kristian.soreide@gmail.com>
=> [Baseline] Properly report Bundle-Version location

bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
The bndtools-m2e plugin created a build loop with certain projects that produced generated Java sources into src/main. The triggering of the jar:jar goal inside BndConfigurator caused sources to regenerate and Eclipse to believe that the project was dirty. This re-enqueued the same project for building, thus creating an infinite loop.
This patch ensures that only the target directory is refreshed. There may be a remaining issue with source generators that generate into `target/generated-sources` but we have been unable to simulate such an issue. It seems that most well-behaved source generator plugins do not get triggered by the jar:jar goal.
=> Eliminate a potential infinite build loop with m2e

bndtools.core/src/org/apache/felix/metatype/AD.java
Javac 9 warns against new wrapper calls.
=> Use wrapper valueOf method instead of new wrapper

bndtools.core/src/bndtools/editor/project/RepositoriesEditModel.java, bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java, bndtools.m2e/_plugin.xml, bndtools.m2e/bnd.bnd, bndtools.m2e/lifecycle-mapping-metadata.xml, bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java
The `bnd-indexer-maven-plugin` is used to generate indexes when using maven. In turn those indexes are used in standalone bndruns when resolving/testing/exporting.
At the moment the only way to get the index to be regenerated is to run a build manually. This is easy to forget, and often means that the index metadata is out of sync with projects in the workspace. The first commit in this PR adds m2e build support for the indexer, including an automatic trigger when any of the indexed workspace project artifacts change.
The second commit in this PR updates the standalone bndrun editor to automatically reload the bnd model when the index changes. This means that the UI and the resolve button always work with up-to-date data after a build of the index, and avoids the user having to …
=> M2E support for the indexer plugin

bndtools.builder/src/org/bndtools/builder/BndProjectInfoAdapter.java, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BuilderPlugin.java, bndtools.builder/src/org/bndtools/builder/ComponentMarker.java, bndtools.builder/src/org/bndtools/builder/decorator/ui/ComponentDecorator.java, bndtools.builder/src/org/bndtools/builder/decorator/ui/PackageDecorator.java, bndtools.builder/src/org/bndtools/builder/decorator/ui/ProjectDecoratorImpl.java, bndtools.core/src/org/bndtools/build/api/IProjectDecorator.java, bndtools.core/src/org/bndtools/build/api/packageinfo, bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
The Bndtools builder adds useful decorations to exported packages, and to files which declare OSGi components. This should be exended to include the maven build as well.
=> Enable ui decorators when using Maven to build

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BuildLogger.java, bndtools.builder/src/org/bndtools/builder/CnfWatcher.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/decorator/ui/ComponentDecorator.java, bndtools.builder/src/org/bndtools/builder/handlers/baseline/BundleVersionErrorHandler.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/WorkspaceListener.java
The Bndtools Builder and Build All (when Build Automatically is off) did not work.
When a project depended on the generated jar of another project, the project's java builder did not rebuild when the dependent jar was built. So the project's build was broken.
These changes fix the Bndtools Builder to properly work with Build All.
=> Fix Build All

bndtools.builder/_plugin.xml, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BuildLogger.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerCompilationParticipant.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, org.bndtools.templating.gitrepo/bnd.bnd, org.bndtools.templating/bnd.bnd
This is a big performance win since we now update the bnd classpath
container before the java builder runs which means the java code is not
compiled with an invalid class path and thus needs to be rebuilt after
we update the classpath in the bnd builder.
We use a CompilationParticipant to get "in front of" the java builder
and update the bnd classpath container if necessary before the java
builder runs. This allows the jars built by dependency projects to be
immediately available to dependent project's java builder.
=> Builder performance boost

bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java
Now that re-indexing is triggered on every dependency change we do a lot more checking of the Maven projects. These checks were done individually, but this turns out to take a long time. This change attempts to reduce the number of check jobs, aggregating the events where possible. I have seen a significant improvement (6 mins -> 16 seconds) as a result - it would be good if others could check this helps them too.
=> Avoid queuing up unnecessary re-indexing jobs

bndtools.core/bnd.bnd, bndtools.m2e/bnd.bnd, org.bndtools.headless.build.plugin.ant/bnd.bnd, org.bndtools.headless.build.plugin.gradle/bnd.bnd, org.bndtools.templating.gitrepo/bnd.bnd, org.bndtools.templating/bnd.bnd
This avoids picking up higher version annotations than intended, including the R7 meta annotated Component which forces a DS 1.4 requirement
=> Move OSGi standard interfaces ahead of bndlib

bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
This was reported at the community event by a Windows user who was unable to run `mvn clean` due to a locked jar file.
=> Avoid holding a file lock when decorating Maven projects

bndtools.builder/src/org/bndtools/builder/decorator/ui/ComponentDecorator.java
This is to address this issue:
Fixes https://github.com/bndtools/bndtools/issues/1774
Signed-off-by: Chris Boyd <wodencafe@gmail.com>
=> Don't decorate parent packages

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/DeltaWrapper.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerCompilationParticipant.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core/src/bndtools/central/Central.java
When the bnd file was modified, the JDT builder had nothing to do and then the BndtoolsBuilder noticed the bnd file and rebuilt the bundle. But unless the JDT builder ran, it would not call the compiler participant which would update the classpath container.
So now the BndtoolsBuilder will update the classpath container when it detects a bnd file change. This can then force the JDT builder to rebuild the source with the updated classpath container.
This is a bit like it was before in that it takes 2 passes through the builders for the change to be fully processed. :-(
=> builder: Request classpath container update when bnd file modified 

bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java
When creating a RepositorySelectionPart, it is possible that
IResourceChangeListener.resourceChanged could be called before
BndEditorPart.refreshFromModel, causing the former to throw an NPE.
Initialize the workspaceIndexFiles field to the empty set to prevent
this.
Fixes #1812
=> Handle potential timing issue in RepositorySelectionPart

bndtools.core/src/bndtools/wizards/bndfile/GenerateLauncherJarRunnable.java
Also, when exporting to a folder, set launch.embedded to false.
Fixes https://github.com/bndtools/bnd/issues/2236
=> export: Use new executablejar exporter

bndtools.release/src/bndtools/release/ReleaseHelper.java, bndtools.release/src/bndtools/release/ReleaseJob.java, bndtools.release/src/bndtools/release/api/ReleaseContext.java
Two problems are resolved by this changeset:
1. When ProjectBuilder goes out of scope it closes all of the JARs in its close list and classpath. When we try to iterate those and get metadata, we get an exception because the JARs are already closed. Instead grab the metadata earlier and save it for later.
2. If a baselining error was present before an 'Update and Release' (i.e. "The bundle version (X.X.X/X.X.X) is too low...") we would throw up a dialog indicating that there was an error during the release when there was none. Instead we now clear the error list after the version update.
=> Fix a few minor problems during release

bndtools.core/src/bndtools/central/Central.java, bndtools.utils/src/org/bndtools/utils/workspace/FileUtils.java
If the Eclipse workspace is constructed where the same file on the file
system is mapped into multiple Eclipse projects, we need to select one
of the resources. There is no way to know the proper answer, but we
choose the resource whose IPath has the smallest segment count. When
mapping the IPath to an IProject, this will return the project "closest"
to the resource.
Fixes https://github.com/bndtools/bndtools/issues/1847
=> central: Map file to shortest path when multiple paths are present

bndtools.core/_plugin.xml, bndtools.core/bnd.bnd, bndtools.core/src/org/bndtools/core/editors/ImportPackageQuickFixProcessor.java, bndtools.core/test/org/bndtools/core/editors/FakeFile.java, bndtools.core/test/org/bndtools/core/editors/ImportPackageQuickFixProcessorAddBundleCompletionProposalTest.java, bndtools.core/test/org/bndtools/core/editors/ImportPackageQuickFixProcessorBndBuildPathHandlerTest.java, bndtools.core/test/org/bndtools/core/editors/ImportPackageQuickFixProcessorTest.java, cnf/ext/central.mvn
This PR is an implementation of #1589.
If you have an import statement for a package/class that is not on the build path, and Bndtools can find one or more bundles that exports that package in the known set of local repositories, then it will add a "quick fixes" to the top of the available quick fixes. Similarly for fully-qualified references to unknown types. 
Bundles from the current workspace will be listed first, then from other repositories.
If you select the "quick fix" for a given bundle, then that bundle will be added to the build path in the `bnd.bnd` file for the current project.
There are some heuristics in there to try to distinguish between class names and package names where it is syntactically ambiguous (basically, in most cases it is assumed to be a package name if it …
=> core: Added quick fixes for missing bundles (implements #1589)

bndtools.core/src/org/bndtools/core/editors/ImportPackageQuickFixProcessor.java, bndtools.core/test/org/bndtools/core/editors/ImportPackageQuickFixProcessorBndBuildPathHandlerTest.java
Quick implementation of a fix for #1865. In summary, altered BndBuildPathHandler so that a bundle is considered to be on its own build path.
This won't work properly on projects that have sub-bundles - that implementation will require a little more surgery (and a little more learning from me on how sub-bundles are structured).
=> Prevent quickfix suggesting that a bundle be added to its own build path

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionWizard.java
This can happen when the resource represents a non-existent bundle.
Fixes https://github.com/bndtools/bndtools/issues/1736
=> resolution: Handle error when resource had no content capability

settings.gradle
If bnd changes, bndtools used the commit timestamp and then p2 would not
download the updated bndtools plugin. This can cause resolution errors
in eclipse between the updated bnd bundles and the older bndtools
bundles.
=> build: Use current time as build time stamp

bndtools.api/.classpath, bndtools.bndplugins/.classpath, bndtools.builder/.classpath, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core/.classpath, bndtools.m2e.debug.fragment/.classpath, bndtools.m2e/.classpath, bndtools.pde/.classpath, bndtools.release/.classpath, bndtools.utils/.classpath, org.bndtools.embeddedrepo/.classpath, org.bndtools.headless.build.manager/.classpath, org.bndtools.headless.build.plugin.ant/.classpath, org.bndtools.headless.build.plugin.gradle/.classpath, org.bndtools.templates.osgi/.classpath, org.bndtools.templates.template/.classpath, org.bndtools.templating/.classpath, org.bndtools.versioncontrol.ignores.manager/.classpath, org.bndtools.versioncontrol.ignores.plugin.git/.classpath
Eclipse Photon now allows classpath entries to be only on test source classpath.
=> testpath: Mark -testpath entries as test=true 

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
Eclipse Photon now supports a separate classpath for test code.
=> testpath: Mark -testpath project entries as without_test_code=true

bndtools.builder/src/org/bndtools/builder/WorkingSetTracker.java, bndtools.core/src/bndtools/wizards/project/ImportBndWorkspaceWizard.java, bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageOne.java, bndtools.pde/src/bndtools/pde/target/RepositoryTargetLocation.java, bndtools.pde/src/bndtools/pde/target/RunDescriptorTargetLocation.java, org.bndtools.templating/src/org/bndtools/templating/util/CompositeOCD.java
Eclipse Photon now supports a separate classpath for test code.
Fixes #1904
=> test: Mark test source entries as test=true 

bndtools.api/src/org/bndtools/api/ProjectPaths.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageOne.java, bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageTwo.java
* ProjectPath changed to hold multiple sources and test sources
* New Wizard now creates class path entries according to the current workspace
=> [newproject] Follows workspace’s settings

org.bndtools.embeddedrepo/bnd.bnd
`warning: Host biz.aQute.bndlib=bundle-version="[4.1.0,5.0.0)" for this fragment cannot be found on the classpath`
=> build: Fix warning from Bnd about fragment host

bndtools.api/bnd.bnd, bndtools.bndplugins/bnd.bnd, bndtools.builder/bnd.bnd, bndtools.core/bnd.bnd, bndtools.jareditor/bnd.bnd, bndtools.m2e.debug.fragment/bnd.bnd, bndtools.m2e/bnd.bnd, bndtools.pde/bnd.bnd, bndtools.release/bnd.bnd, bndtools.utils/bnd.bnd, build/feature/bndtools/feature.xml, build/main.bnd, cnf/build.bnd, cnf/ext/central.mvn, org.bndtools.embeddedrepo/bnd.bnd, org.bndtools.headless.build.manager/bnd.bnd, org.bndtools.headless.build.plugin.ant/bnd.bnd, org.bndtools.headless.build.plugin.gradle/bnd.bnd, org.bndtools.headless.build.plugin.gradle/resources/templates/filter/root/gradle.properties, org.bndtools.templating.gitrepo/bnd.bnd, org.bndtools.templating/bnd.bnd, org.bndtools.versioncontrol.ignores.manager/bnd.bnd, org.bndtools.versioncontrol.ignores.plugin.git/bnd.bnd
Remove use of javax.xml bundles since the API is part of Java 8+. Use
repo contents to control version of osgi jars uses in build instead of
a variable.
=> build: Some build cleanup

bndtools.core/src/bndtools/views/repository/RepositoriesView.java
Chasing an exception in refreshing plugins. We only
show the target exception and no trace. This
adds a trace into the log.
Signed-off-by: Peter Kriens <Peter.Kriens@aqute.biz>
=> [repositoriesview] Logging the target exception

bndtools.core/src/bndtools/wizards/project/AbstractNewBndProjectWizard.java
The project is not picked up by bnd otherwise, and the buildpath is not set.
Signed-off-by: PK Søreide <per.kristian.soreide@gmail.com>
=> Fix: Refresh ProjectTracker when NewBndProjectWizard is done

org.bndtools.templating/bnd.bnd
The updated Bnd now finds Class.forName references to these packages
in guava and imports them. Since we do not really care about them, we
make the imports optional so we can resolve in Eclipse.
=> templating: Make google appengine/apphosting package imports optional

org.bndtools.templating.gitrepo/bnd.bnd
The updated Bnd now finds Class.forName references to these packages
in jgit and imports them. We make the imports optional so we can resolve
in Eclipse.
=> gitrepo: Make sun package imports optional

cnf/ext/central.mvn, settings.gradle
This is now needed by the latest Bnd gradle plugin.
=> Add mavenCentral() to buildscript classpath 
