bndtools.jareditor/src/bndtools/jareditor/internal/JARContentTreePart.java

Signed-off-by: Sean Bright <sean@malleable.com>

Jar Viewer: Expand/collapse directories on double click

---

bndtools.core/src/bndtools/editor/project/RepositoryBundleSelectionPart.java

See https://github.com/bndtools/bnd/pull/744 for same issue but on bndlib side.

Sanitize URIs for when dropped from external browser

---

bndtools.core/src/bndtools/editor/project/RepositoryBundleSelectionPart.java

These are cherry picked from master.

Additional fixes for 2.4.1

---

bndtools.repository.base/templates/unprocessed/common/build.bnd

Fixes https://github.com/bndtools/bndtools/issues/970

Add javac.profiles to defaults

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

Handles the case where:
Java Project A outputs a.jar containing package A
OSGI Project B has a version=file reference to a.jar and includes package A in export-packages.
OSGI Project C has buildpath reference to B and uses something in package A.
Without this change, Project C couldn't build due to
"not accessible due to restriction on required project" errors
Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>

Fix transition jar file references issue

---

bndtools.builder/src/org/bndtools/builder/NewBuilder.java

Trial attempt to speed up the build

---

bndtools.builder/src/org/bndtools/builder/NewBuilder.java

Set the build order in Eclipse on bnd build order

---

bndtools.builder/src/org/bndtools/builder/NewBuilder.java

Reverts bndtools/bndtools#1006
Peter says this did not work out well and needs more work.

Revert "Set the build order in Eclipse on bnd build order"

---

bndtools.builder/src/org/bndtools/builder/NewBuilder.java

[builder] Define the order of the Eclipse build based on bnd order

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

Tidied up the class in preparation for removal of old classpath entries.
- Added project as sourcepath to library entries
- Added access rules which hide the project entry that is paired with
the library entry
- Added access rules to the library entry
- Changed access rule calculation to be Container based rather than
project based since the rules are applied to the classpath entry
representing the container.
Discuss in #1005.

builder: Improvements to new classpath container implementation

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

- Added packages attribute to extra classpath attributes
- If packages attribute used, it is the authority overriding other info
- For version=project, use Project.getExports for access rules
- Add access rules for REPO and EXTERNAL Container types
- If no Bundle-ManifestVersion header, grant full access
Discuss in #1005.

builder: More improvements to new classpath container implementation

---

bndtools.api/bnd.bnd
bndtools.bndplugins/repos.bnd
bndtools.builder/bnd.bnd
bndtools.core/bnd.bnd
bndtools.jareditor/bnd.bnd
bndtools.release/bnd.bnd
bndtools.repository.amdatu/bnd.bnd
bndtools.repository.base/bnd.bnd
bndtools.repository.maven/bnd.bnd
bndtools.template.amdatu/bnd.bnd
bndtools.template.dm/bnd.bnd
bndtools.utils/bnd.bnd
build/main.bnd
cnf/build.bnd
org.bndtools.embeddedrepo/bnd.bnd
org.bndtools.headless.build.manager/bnd.bnd
org.bndtools.headless.build.plugin.ant/bnd.bnd
org.bndtools.headless.build.plugin.gradle/bnd.bnd
org.bndtools.versioncontrol.ignores.manager/bnd.bnd
org.bndtools.versioncontrol.ignores.plugin.git/bnd.bnd

Sync version with bnd for next release.
Fixes https://github.com/bndtools/bndtools/issues/996

build: Update to version 3.0

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

Only path segments of * will be replaced with **. A path segment which
contains * is unchanged.

classpath: Improve packages attribute processing

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

classpath: Simplify regex to only have two match values

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
bndtools.utils/src/org/bndtools/utils/jar/JarUtils.java

More fixes for the classpath implementation.

Classpath fixes

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
bndtools.builder/src/org/bndtools/builder/MarkerSupport.java

- Builder exceptions in setting markers
- Refresh model before calculating dependsOn

Builder fixes

---

org.bndtools.embeddedrepo/bnd.bnd
org.bndtools.embeddedrepo/bnd/embedded-repo.bnd

embedded-repo: Use embedded repo built in bnd build

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

This will allow -testpath errors to be marked on the -testpath header
instead of always being on the -buildpath header.

classpath: Refactor to allow errors to be marked on the proper header

---

bndtools.builder/bnd.bnd
bndtools.core/bnd.bnd
bndtools.core/src/bndtools/editor/completion/BndHover.java
bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java
bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
bndtools.core/src/bndtools/launch/bnd/LaunchThread.java
bndtools.core/src/bndtools/launch/ui/ProjectLaunchTabPiece.java
bndtools.core/src/org/bndtools/build/api/AbstractBuildErrorDetailsHandler.java
bndtools.core/src/org/bndtools/core/ui/wizards/ds/NewTypeWizardPage.java
bndtools.release/bnd.bnd
settings.gradle

Also some other fixes for remove warnings and compile with java 8.

Fix compilation error introduced by a bnd change

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java

If the build order changed, the check for class path changes was never executed. Now when there is a setup change, they are both executed. If either had a change, we postpone.

[builder] Build order change did then never check for class path change

---

bndtools.core/src/org/bndtools/core/ui/wizards/blueprint/BlueprintXmlFileWizard.java

[blueprint wizard] Better handle empty headers when setting up the blueprint - Fixes #1048

---

bndtools.builder/src/org/bndtools/builder/decorator/ui/PackageDecorator.java

builder: Update package decoration version only if changed

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

Optimize reading of jars by caching results in a weak hash map.

classpath: update sourcepathattachment logic

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

classpath: JarInfo inner class should be static

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

- correct spelling of argument name
- log IOException instead of discarding it
- don't bother reading jar file if it does not exist
- remove superfluous project existence check since isOpen includes it

classpath: minor fixes

---

bndtools.builder/src/org/bndtools/builder/CnfWatcher.java
bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
bndtools.utils/src/org/bndtools/utils/workspace/WorkspaceUtils.java

Also demote logging to error since it is normal in the new project in
empty workspace scenario.
Related to https://github.com/bndtools/bndtools/issues/1069

builder: Fix NPE during new project creation in empty workspace

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
bndtools.builder/src/org/bndtools/builder/validate/BsnValidator.java
bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java
bndtools.core/src/bndtools/wizards/project/AbstractNewBndProjectWizard.java
bndtools.core/src/org/bndtools/build/api/AbstractBuildErrorDetailsHandler.java
bndtools.test/bndws/cnf/ext/javac.bnd
bndtools.test/bndws/launch.simple/.classpath
bndtools.test/bndws/launch.simple/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.bottom/.classpath
bndtools.test/bndws/test.bottom/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.decoration/.classpath
bndtools.test/bndws/test.decoration/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.dependson/.classpath
bndtools.test/bndws/test.dependson/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.exports.external/.classpath
bndtools.test/bndws/test.exports.external/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.subbundles.api/.classpath
bndtools.test/bndws/test.subbundles.api/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.subbundles.apiconsumer/.classpath
bndtools.test/bndws/test.subbundles.apiconsumer/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/test.top/.classpath
bndtools.test/bndws/test.top/.settings/org.eclipse.jdt.core.prefs
bndtools.test/bndws/validators/.classpath

Clean up some corner case exceptions when you have malformed workspace (no cnf).

Builder clean exception

---

bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java

A project may not have a test folder. So only warn if the test folder
exists and is not mentioned in the eclipse classpath.
Also removed duplicate warnings for bin and bin_test issues.
Fixes https://github.com/bndtools/bndtools/issues/1076

paths validator: Clean up warnings and don't warn if no test folder

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java

Also last modified methods now have default access.

classpath container: Use AtomicLong instead of volatile/synchronized

---

bndtools.core/resources/unprocessed/schema/projectTemplates.exsd

Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

Added missing schema information for template attributes

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

Fixes https://github.com/bndtools/bndtools/issues/1078.

classpath: Ignore Discouraged if better access later in classpath

---

bndtools.core/_plugin.xml

Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

Change shortcut fixes #1054

---

org.bndtools.headless.build.plugin.gradle/resources/templates/filter/root/gradle.properties

Fixes https://github.com/bndtools/bnd/issues/919

gradle template: Use proper macro name for bnd version

---

.travis.yml

travis: Test under jdk8 as well as jdk7

---

bndtools.api/src/org/bndtools/api/ProjectPaths.java

Maven layout template - fixes bndtools/bndtools#1125

---

bndtools.core/_plugin.xml
bndtools.test/bndws/launch.simple/bnd.bnd
bndtools.test/bndws/launch.simple/liferay.bndrun
bndtools.test/bndws/launch.simple/remote.bndrun
bndtools.test/bndws/launch.simple/servlet.bnd

This requires https://github.com/bndtools/bnd/pull/909

added shortcuts and liferay+jmx example

---

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionFailurePanel.java

Signed-off-by: Marc Schlegel <maschlegel@gmail.com>

Add vertical scrollbar to resolution-error-textarea

---

bndtools.core/resources/enroute/osgi.enroute.template/_test_/bnd.bnd
bndtools.core/resources/enroute/readme.md

[tester] -testpath must not be set in OSGi testing

---

bndtools.builder/src/org/bndtools/builder/DeltaWrapper.java

[builder] NPE when path did not exist

---

bndtools.core/src/bndtools/launch/bnd/NativeBndLaunchDelegate.java

[build] bnd declared an IOException on Processor.close

---

bndtools.bndplugins/src/bndtools/bndplugins/repo/git/GitUtils.java
cnf/ext/repositories.bnd

This uses the Eclipse 4.3.2 bundles in bintray at https://dl.bintray.com/bndtools/eclipse-repo/4.3.2/.

Update base Eclipse version to Kepler 4.3.2

---

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionSuccessPanel.java

[resolve] Fixed NPE on resolve

---

org.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/root/build.gradle
org.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/root/settings.gradle

gradle: Update template to latest gradle scripts

---

bndtools.core/resources/enroute/osgi.enroute.template/_application_/src/_package_/_stem_Application.java
bndtools.core/resources/enroute/osgi.enroute.template/_example_/src/_package_/command/_stem_Command.java

enroute template

---

bndtools.core/resources/enroute/osgi.enroute.template/_webresource_/bnd.bnd

[template] enRoute template update

---

build.gradle

build: Log full exception for test failures

---

build/build.gradle
build/feature/extras/amdatu/feature.xml
build/feature/extras/dm/feature.xml
build/feature/main/bndtools/feature.xml

Fix update site in feature.xml

---

bndtools.core/src/bndtools/Activator.java

Make sure repoindex bundle starts

---

bndtools.core/src/bndtools/launch/api/AbstractLaunchShortcut.java

Bug in standalone run when cnf does not exist

---

bndtools.core/src/bndtools/wizards/project/ProjectLocationGroup.java
bndtools.core/src/org/bndtools/core/ui/util/SWTUtil.java

Signed-off-by: Sean Bright <sean@malleable.com>

Fixes to New Project Wizard

---

build/bnd.bnd

Missed plugin from feature

---

bndtools.utils/src/org/bndtools/utils/resources/ResourceUtils.java

[resource] Resources are permitted to have multiple content capabilities

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java

bndlib is not thread safe so we must serialize access to bndlib in the
builder. We already did this for the classpath initializer and now do
it for the builder.
Fixes https://github.com/bndtools/bndtools/issues/1194

builder: bndlib thread safety

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java

bndlib is not thread safe so we must serialize access to bndlib in the
builder. We already did this for the classpath initializer and now do
it for the builder.
Fixes https://github.com/bndtools/bndtools/issues/1194

builder: bndlib thread safety (part 2)

---

org.bndtools.embeddedrepo/bnd.bnd

Fixes #1214
Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

Add imports needed by some classes in biz.aQute.remote.launcher

---

bndtools.core/src/bndtools/launch/OSGiJUnitLaunchDelegate.java

Avoid running  all tests when a single method is requested

---

bndtools.bndplugins/bnd.bnd
bndtools.builder/bnd.bnd
bndtools.builder/src/org/bndtools/builder/handlers/baseline/BundleVersionErrorHandler.java
bndtools.core/src/bndtools/HeadlessBuildManagerTracker.java
bndtools.core/src/bndtools/central/WorkspaceListener.java
bndtools.core/src/bndtools/editor/common/MapEntryCellModifier.java
bndtools.core/src/bndtools/editor/project/RepositoryBundleSelectionPart.java
bndtools.core/src/bndtools/editor/project/RunBundlesPart.java
bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java
bndtools.core/src/bndtools/preferences/ui/BndBuildPreferencePage.java
bndtools.core/src/bndtools/wizards/project/AbstractNewBndProjectWizard.java
bndtools.core/src/bndtools/wizards/workspace/CnfSetupTask.java
bndtools.core/src/org/bndtools/build/api/AbstractBuildErrorDetailsHandler.java
bndtools.core/src/org/bndtools/core/ui/wizards/index/GenerateIndexCommandHandler.java
bndtools.core/src/org/bndtools/core/ui/wizards/index/NewIndexWizard.java
bndtools.jareditor/src/bndtools/jareditor/internal/JAREditor.java
org.bndtools.headless.build.manager/src/org/bndtools/headless/build/manager/HeadlessBuildManagerImpl.java
org.bndtools.headless.build.plugin.ant/src/org/bndtools/headless/build/plugin/ant/AntHeadlessBuildPlugin.java
org.bndtools.headless.build.plugin.gradle/src/org/bndtools/headless/build/plugin/gradle/GradleHeadlessBuildPlugin.java

Some are for javac, some are for ECJ.

Fix a number of compiler warnings in the build

---

bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java

Saving the editor when it wasn't dirty prior to resolution.
Signed-off-by: Marc Schlegel <marc.schlegel@gmx.de>

1210: Simplify resolution of requirements to bundles

---

org.bndtools.templates.osgi/bnd.bnd
org.bndtools.templates.template/bnd.bnd

Fix build errors on Cloudbees

---

bndtools.core/.settings/org.eclipse.jdt.core.prefs
bndtools.core/src/bndtools/central/Central.java
bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java
bndtools.core/src/bndtools/central/WorkspaceRepositoryChangeDetector.java
bndtools.core/src/bndtools/editor/project/AvailableBundlesPart.java
bndtools.core/src/bndtools/views/repository/RepositoriesView.java

We had no mechanism in place for updating view with the repositories contents

#1212 Bundles not showing in the available list and no auto update of repo view

---

org.bndtools.templating/src/org/bndtools/templating/TextResource.java
org.bndtools.templating/src/org/bndtools/templating/repobased/StringTemplateEngine.java

Silence eclipse warnings in org.bndtools.templating

---

bndtools.builder/src/org/bndtools/builder/listeners/CnfSetupBuildListener.java
bndtools.builder/src/org/bndtools/builder/validate/JavaVersionsValidator.java
bndtools.core/src/bndtools/central/Central.java
bndtools.core/src/bndtools/editor/project/AvailableBundlesPart.java
bndtools.core/src/bndtools/views/repository/RepositoriesView.java

Also fix an exception I found in the error log.

Fix NPE in issue 1199

---

bndtools.core/src/bndtools/central/Central.java
bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java
bndtools.core/src/bndtools/central/RepositoryUtils.java

Added locking around repository actions.
Fixes https://github.com/bndtools/bndtools/issues/1259

deadlock: WorkspaceRepository refresh deadlock with building

---

bndtools.core/src/bndtools/views/repository/RepositoriesView.java

Call TreeViewer.refresh() on the UI thread

---

bndtools.core/src/bndtools/editor/project/RepositoryBundleSelectionPart.java
bndtools.core/src/bndtools/model/repo/RepositoryResourceElement.java
bndtools.core/src/bndtools/model/repo/RepositoryTreeContentProvider.java

I'm not convinced that this is the most elegant way of implementing
this, so feedback is certainly appreciated.
Fixes #1230
Signed off by: Sean Bright <sean.bright@gmail.com>

Add DnD support for advanced search results.

---

bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java

Prevent the user from clicking the Resolve button multiple times in a row.

---

bndtools.core/src/bndtools/utils/JavaLangUtils.java
bndtools.core/src/bndtools/wizards/project/ProjectNameGroup.java

Validate package names against Java language keywords

---

bndtools.core/src/bndtools/views/repository/RepositoriesView.java

A URL that does not contain ".jar" might still return one, so check it after we
download to be sure. The special case for JPM was left in place.

Handle URLs that don't contain the phrase ".jar"

---

bndtools.core/bndtools.shared.bndrun
org.bndtools.templating.gitrepo/bnd.bnd

Embed required jgit packages

---

bndtools.core/src/org/bndtools/core/templating/repobased/BundleLocator.java
bndtools.core/src/org/bndtools/core/templating/repobased/CapabilityBasedTemplate.java
bndtools.core/src/org/bndtools/core/templating/repobased/DirectDownloadBundleLocator.java
bndtools.core/src/org/bndtools/core/templating/repobased/RepoPluginsBundleLocator.java
bndtools.core/src/org/bndtools/core/templating/repobased/ReposTemplateLoader.java
bndtools.core/test/org/bndtools/core/templating/repobased/ReposTemplateLoaderTest.java

Temp fix for downloading of templates when workspace doesn’t exist

---

bndtools.core/src/bndtools/wizards/bndfile/BndRunFileWizard.java
bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java
bndtools.core/src/bndtools/wizards/project/ProjectTemplateParam.java
bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizard.java
bndtools.core/src/org/bndtools/core/ui/wizards/shared/ISkippableWizardPage.java
bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateParamsWizardPage.java
bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java
org.bndtools.templating/src/org/bndtools/templating/engine/st/StringTemplateEngine.java

[template] Parameter entry page on template wizards

---

bndtools.bndplugins/bnd.bnd
bndtools.core/bnd.bnd
bndtools.core/bndtools.e4.shared.bndrun
bndtools.core/bndtools.shared.bndrun
build/feature/bndtools/feature.xml
build/main.bnd
cnf/jpm4j.json

Add slf4j to feature so bndlib will resolve.

build: bndlib uses slf4j

---

bndtools.core/src/bndtools/tasks/AnalyseBundleResolutionJob.java
bndtools.test/bndws/test.maven/.gitignore

gitignore generated

---

build.gradle
gradle.properties
settings.gradle

Get gradle plugin from maven shaped repo

Maven repos

---

bndtools.api/src/org/bndtools/api/ProjectPaths.java
bndtools.api/src/org/bndtools/api/package-info.java
bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java
bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageOne.java
bndtools.core/src/bndtools/wizards/project/ProjectLayoutGroup.java

Fix #1277: Remove Maven layout option

---

bndtools.manual/site/installation.html

Update website for 3.2 release

---

bndtools.core/bnd.bnd
bndtools.core/src/org/apache/felix/metatype/AD.java
bndtools.core/src/org/apache/felix/metatype/ADValidator.java
bndtools.core/src/org/apache/felix/metatype/Attribute.java
bndtools.core/src/org/apache/felix/metatype/Designate.java
bndtools.core/src/org/apache/felix/metatype/DesignateObject.java
bndtools.core/src/org/apache/felix/metatype/MetaData.java
bndtools.core/src/org/apache/felix/metatype/MetaDataReader.java
bndtools.core/src/org/apache/felix/metatype/OCD.java
bndtools.core/src/org/apache/felix/metatype/OptionalAttributes.java
bndtools.core/src/org/bndtools/core/templating/repobased/CapabilityBasedTemplate.java
bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateParamsWizardPage.java

Use Metatype spec info for template parameters

---

bndtools.core/bndtools.shared.bndrun

Fix resolution errors in debug launch

---

bndtools.core/src/org/bndtools/core/templating/repobased/CapabilityBasedTemplate.java

Fix possible NPE in getMetadata

---

bndtools.core/src/org/bndtools/core/templating/repobased/ReposTemplateLoader.java

Fixed erroneous import (well spotted PK!)

---

bndtools.core/src/bndtools/editor/pages/ProjectRunPage.java
bndtools.core/src/bndtools/editor/project/RunBlacklistPart.java

fixes bndtools/bndtools#1397
implements a new section in the run-requirements to handle blacklisting bundles for resolution.
Signed-off-by: Marc Schlegel <maschlegel@gmail.com>

1397: Provide support for -runblacklist

---

bndtools.core/src/bndtools/editor/pages/ProjectRunPage.java

Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

fixes https://github.com/bndtools/bndtools/pull/1421#issuecomment-228571144

---

bndtools.core/src/bndtools/editor/project/OSGiFrameworkContentProvider.java

Exception was thrown by getRepositories

---

bndtools.builder/bnd.bnd
bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
bndtools.core/bnd.bnd
bndtools.core/src/bndtools/central/JobProgress.java
bndtools.core/src/org/apache/felix/metatype/AD.java
bndtools.core/src/org/apache/felix/metatype/ADValidator.java
bndtools.core/src/org/apache/felix/metatype/DesignateObject.java
bndtools.core/src/org/apache/felix/metatype/MetaData.java
bndtools.core/src/org/apache/felix/metatype/MetaDataReader.java
bndtools.core/src/org/apache/felix/metatype/OCD.java
bndtools.core/src/org/apache/felix/metatype/OptionalAttributes.java

Job and Task are same class now;  AtomicReference is used to
communicate result and done status between threads; job name is logged.
Also some build fixes.

Update JobProgress implementation

---

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionWizard.java

[resolve] NPE when -runbundles is not set on Resolve Finish

---

bndtools.test/bndws/launch.simple/really.bndrun
bndtools.test/bndws/launch.simple/remote.bndrun
bndtools.test/bndws/launch.simple/servlet.bndrun
org.bndtools.templates.osgi/resources/templates/ds/launch.bndrun
org.bndtools.templates.osgi/resources/templates/launch/felix-gogo/$fileName$
org.bndtools.templates.template/resources/templates/bndrun/resources/template/$fileName$

Closes https://github.com/bndtools/bnd/issues/1471

bnd: Use -runprovidedcapabilities to specify native capabilities

---

bndtools.core/src/bndtools/central/JobProgress.java

progress: Handle InterruptedException as a cancel

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

Fixes https://github.com/bndtools/bndtools/issues/1430

container: Properly initialize bnd class path container when requested

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
bndtools.builder/src/org/bndtools/builder/classpath/ClasspathContainerSerializationHelper.java

Clean up some names to be better. Use static member classes for
ObjectInputStream and ObjectOutputStream subclasses.

classpath container: Tidy up

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/ui/GitRepoTemplatePreferencePage.java

Repositores -> Repositories

---

bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizardPage.java

Don't use ALL CAPS

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitRepoPreferences.java
org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/ui/GitRepoTemplatePreferencePage.java

GitRepo prefs: ScopedPreferenceStore is not saved automatically

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitCloneTemplate.java

GitHub repos: Set correct remote when not specified

---

bndtools.core/src/bndtools/central/Central.java
bndtools.core/src/bndtools/editor/BndEditor.java
bndtools.core/src/bndtools/editor/common/UpDownButtonBarPart.java
bndtools.core/src/bndtools/editor/project/AvailableBundlesPart.java
bndtools.core/src/bndtools/editor/project/RepositoriesEditModel.java
bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java

- Ordering and editing now works fine
- No more need to save when switching between standalone/workspace
- Organized code

[standalone] Seriously improved the support for -standalone

---

bndtools.core/src/bndtools/central/Central.java

setting up a new eclipse workspace.

central: Revert changes to getWorkspace since it breaks the flow of

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitCloneTemplate.java

Unbreak Git repo tag support

---

bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizard.java

Implementation suggested by @gamerson
Fixes #1480

Load workspace repositories when workspace wizard finishes

---

bndtools.core/src/bndtools/central/Central.java
bndtools.core/src/bndtools/central/RepositoryUtils.java
bndtools.core/src/bndtools/editor/BndEditor.java

Should solve the problems with async updates of repos.
Need to discuss

BndEditor and repository asynchrony

---

bndtools.core/src/bndtools/central/RepositoryUtils.java

Remove an unused field.

---

bndtools.core/src/bndtools/WorkspaceServiceFactory.java
bndtools.core/src/bndtools/editor/workspace/WorkspaceMainPart.java
bndtools.core/src/bndtools/launch/BndDependencySourceContainer.java
bndtools.core/src/bndtools/launch/bnd/NativeBndLaunchDelegate.java
bndtools.core/src/bndtools/launch/util/LaunchUtils.java
bndtools.core/src/bndtools/nature/ToggleNatureAction.java
bndtools.core/src/bndtools/preferences/ui/ReposPreferencePage.java
bndtools.core/src/bndtools/tasks/AnalyseBundleResolutionJob.java
bndtools.core/src/bndtools/tasks/BndFileCapReqLoader.java
bndtools.core/src/bndtools/views/repository/RepositoriesView.java
bndtools.core/src/bndtools/wizards/project/ProjectLocationGroup.java
bndtools.core/src/bndtools/wizards/workspace/WorkspaceLocationPart.java
bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizardPage.java
bndtools.core/src/org/bndtools/core/ui/wizards/blueprint/BlueprintXmlFileWizard.java
bndtools.core/src/org/bndtools/core/ui/wizards/blueprint/WizardBndFileSelector.java
bndtools.test/workspace-comms/cnf/settings.gradle
bndtools.test/workspace-comms/settings.gradle
org.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/root/settings.gradle

Be really nit-picky about how Bnd is displayed (BND -> Bnd)

---

bndtools.core/src/bndtools/views/repository/RepositoriesView.java

Escape ampersands (`&`) in Action labels

---

bndtools.core/src/bndtools/views/repository/RepositoriesView.java

This fixes the NPE that is references in bug: https://github.com/bndtools/bnd/issues/1620
Signed-off-by: Luke Winkenbach <lukewink@gmail.com>

Fix NPE when artifact download fails

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitRepoPreferences.java

Fixes https://github.com/bndtools/bnd/issues/1594

Update bndtools/workspace template to point to 3.3 branch

---

gradle.properties

Remove trailing whitespace

---

bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java

Make dismissing the "Errors in running OSGi Framework" easier

---

bndtools.core/src/bndtools/editor/pages/ProjectRunPage.java

Only update the UI on the UI thread.

---

bndtools.core/_plugin.xml
bndtools.core/src/bndtools/PartConstants.java
bndtools.core/src/bndtools/perspective/BndPerspective.java

Promote Bnd OSGi Workspace to the "New" menu

---

bndtools.core/_plugin.xml
bndtools.core/src/bndtools/PartConstants.java
bndtools.core/src/bndtools/perspective/BndPerspective.java

This reverts commit bd78d3fe4d12921cc74a4f37255b1841be25b03d, reversing
changes made to b8e4935db89386f7fb2f2b514256560b6145f0f1.

Revert "Merge pull request #1525 from seanbright/workspace-wiz-proj"

---

bndtools.core/src/bndtools/views/repository/RepositoriesView.java

Expand repositories in Repositories view on double click

---

bndtools.repository.base/_plugin.xml
bndtools.repository.base/bnd.bnd
bndtools.repository.base/templateDocs/BundleHubConfig.xml

Fix some issues with the legacy template support

---

bndtools.core/src/org/bndtools/core/ui/wizards/shared/RepoTemplateLabelProvider.java
bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java

If a project template doesn't have an icon, use a default one.

---

bndtools.repository.base/templates/unprocessed/bundlehub/ext/repositories.bnd

Switch Bundle Hub workspace template to use OSGiRepository

---

bndtools.core/src/bndtools/launch/util/LaunchUtils.java

Fixes #1591: Exception after renaming project referenced from launch configuration

Clarify exception message in LaunchUtils

---

CONTRIBUTING.md

Fix typo in development environment section

---

build/bnd.bnd

Add osgi.enroute.bndtools.templates to build list

---

osgi.enroute.bndtools.templates/bnd.bnd

Fix category name on new enRoute templates

---

bndtools.core/src/bndtools/editor/BndEditor.java

This ensures that IDocumentProvider is checked for null when used in BndEditor, as this item can be null if the form is disposed.

Check for null when using IDocumentProvider #1625

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

The output folder is no longer in the buildpath.

buildpath: Remove output folder from buildpath

---

bndtools.core/src/bndtools/launch/api/AbstractLaunchShortcut.java

Fixes https://github.com/bndtools/bndtools/issues/1661

only set the ATTR_PROJECT_NAME if target project is indeed a java project

---

bndtools.test/workspace-comms/cnf/gradle.properties
bndtools.test/workspace-comms/gradle.properties
gradle.properties
org.bndtools.headless.build.plugin.gradle/resources/templates/filter/root/gradle.properties
settings.gradle

Use new Bnd Gradle plugin support to configure the workspace object.

Build fixes

---

bndtools.builder/src/org/bndtools/builder/WorkingSetTracker.java

- Update direct, not in async display
- Check for workingset name, must now be a Java identifier
- Added warning when name is wrong

[workingsets] Improvements from feedback

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitRepoPreferences.java

We use new enroute template repo and update branch for bndtools template.

templates: Update GitHub URLs for workspace templates

---

bndtools.core/src/bndtools/editor/project/messages.properties
bndtools.core/src/bndtools/preferences/ui/messages.properties

Unused NLS messages

---

bndtools.core/src/bndtools/RefreshReposHandler.java

There is nothing remarkable about a Refreshable returning false.

---

bndtools.release/src/bndtools/release/ReleaseHelper.java
build/main.bnd
cnf/build.bnd
org.bndtools.embeddedrepo/bnd.bnd
org.bndtools.headless.build.plugin.ant/bnd.bnd
org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/Cache.java
org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitHub.java

Use new PromiseExecutor and some other fixes.

Promise executor

---

bndtools.release/src/bndtools/release/DiffHelper.java

Fixes #828 
Signed-off-by: PK Søreide <per.kristian.soreide@gmail.com>

Fixes 828 - release: doesn't respect -baselinerepo instruction

---

bndtools.m2e/src/bndtools/m2e/BndConfigurator.java

When trying out the latest code I experienced NPEs from the Bnd M2E builder. It happens when I force a Maven project update offline:
java.lang.NullPointerException
at bndtools.m2e.BndConfigurator$1$1.runInWorkspace(BndConfigurator.java:61)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
I'm not an Eclipse expert, but it seems as though we should always be using the monitored version of getMavenProject() if the unmonitored one returns null...

MavenProject can still be null when refreshing Maven metadata

---

.travis.yml
bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
bndtools.builder/src/org/bndtools/builder/handlers/baseline/BundleVersionErrorHandler.java
bndtools.core/src/bndtools/editor/project/RunBundlesPart.java
bndtools.core/src/bndtools/model/repo/RepositoryTreeContentProvider.java
bndtools.core/src/bndtools/tasks/BndFileCapReqLoader.java
bndtools.release/src/bndtools/release/DiffHelper.java
bndtools.release/src/bndtools/release/ReleaseDialogJob.java
bndtools.release/src/bndtools/release/ReleaseHelper.java
bndtools.release/src/bndtools/release/WorkspaceAnalyserJob.java
bndtools.release/src/bndtools/release/ui/ProjectListControl.java
build/build.gradle

There were a number of cases where the builders were not properly closed.
See also https://github.com/bndtools/bnd/pull/2093 for similar changes to Bnd.

locked files: Properly close builders

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
bndtools.builder/src/org/bndtools/builder/jobs/newproject/AdjustClasspathsForNewProjectJob.java
bndtools.builder/src/org/bndtools/builder/jobs/newproject/NewProjectResourceListener.java
bndtools.core/src/bndtools/central/Central.java
bndtools.utils/src/org/bndtools/utils/jar/PseudoJar.java

Several improvements to improve performance in workspaces with hundreds of bndtools projects.

Performance Fixes

---

bndtools.builder/src/org/bndtools/builder/jobs/newproject/AdjustClasspathsForNewProjectJob.java

It does not add useful information to the log.

classpath: Remove log message

---

bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java

Avoid NPE when the MavenProject has no artifact file

---

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
bndtools.core/src/bndtools/central/Central.java
bndtools.core/src/bndtools/central/RefreshFileJob.java
bndtools.core/src/bndtools/central/WorkspaceListener.java

Some errors fixes found when adding new projects to an Eclipse workspace.

Error fixes

---

bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java

resolve: Change ResolveLogger to AutoClosable

---

org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitRepoPreferences.java

template: Update version to make current build version

---

bndtools.core/_plugin.xml
bndtools.core/src/bndtools/editor/BndEditor.java
bndtools.core/src/org/bndtools/core/resolve/ResolveJob.java

Fixes to toolbar resolve button (only want one!)

---

bndtools.core/_plugin.xml
bndtools.core/src/bndtools/StatusCode.java
bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
bndtools.core/src/bndtools/launch/ui/internal/NoVMForEEStatusHandler.java

Use the value of -runee to choose a launch JVM

---

bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java

Fix #1807: NPE in m2e IndexConfigurator

---

bndtools.core/src/org/bndtools/core/ui/resource/R5LabelFormatter.java
bndtools.utils/src/org/bndtools/utils/jface/ImageCachingLabelProvider.java

Fix missing image icon paths

---

bndtools.core/src/bndtools/editor/BndEditor.java
bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java

Disable resolve buttons during resolve job

---

bndtools.core/src/bndtools/model/repo/RepositoryEntry.java

Fixes https://github.com/bndtools/bndtools/issues/1824

repoentry: Unwrap InvocationTargetException from repo before logging

---

.gradle-wrapper/gradle-wrapper.properties
build.gradle
cnf/build.bnd

Build reproducible jars with new support in Bnd.

Reproducible jars

---

bndtools.core/src/org/bndtools/core/editors/ImportPackageQuickFixProcessor.java
bndtools.core/test/org/bndtools/core/editors/ImportPackageQuickFixProcessorTest.java

While using this new feature on another repo, I discovered an additional Eclipse problem type where Bndtools could offer useful suggestions. Was straightforward to implement.

Add quickfix suggestions for Eclipse problems of type IProblem.IsClassPathCorrect

---

bndtools.core/src/bndtools/editor/BndEditor.java

BndEditor: Prevent invalid thread access during resolution

---

bndtools.builder/src/org/bndtools/builder/indexer/BuiltBundleIndexer.java
bndtools.core/src/org/bndtools/core/jobs/GenerateIndexJob.java

indexer: Convert SimpleIndexer to fluid builder API

---

bndtools.core/src/bndtools/central/Central.java

We now also include the thread owner name and stacktrace in the timeout
exception.
See https://github.com/bndtools/bndtools/issues/1881

central: Add more diagnostic info to bndCall timeout exeception

---

bndtools.core/src/bndtools/central/Central.java

The stacktrace of the owner thread is now the stacktrace of the owner
thread at the time the lock failed to be acquired by the caller rather
than the stacktrace of the owner thread at the time the owner thread
acquired the lock.
See https://github.com/bndtools/bndtools/issues/1881

central: Add more diagnostic info to bndCall timeout exception

---

bndtools.core/src/bndtools/launch/OSGiJUnitLaunchDelegate.java

Fixes #1891
Signed-off-by: Thomas Watson <tjwatson@us.ibm.com>

Use transient start instead of persistent

---

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java

If no source folder is marked test=true, then -testpath entries are not
marked test=true.

testpath: Only mark -testpath entries test=true when a test source found

---

bndtools.api/bnd.bnd

[build] Missed Strings as conditional package

---

bndtools.core/src/bndtools/editor/contents/GeneralInfoPart.java

This drop down is now more confusing than it is useful. Standard DS annotation processing is always on, and the old annotations are deprecated. User interaction with this property is therefore extremely rare, and so a dropdown selector on the "main" bnd.bnd editor page is not desirable.

Remove the DS annotations drop down from the Bundle Content editor panel
